<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-N478O9TO" failures="1" tests="6" name="Test" time="272.026" errors="0" timestamp="2023-06-17T21:44:21 IST">
  <testcase classname="placeOrder.placeOrder" name="launchApp" time="2.39"/>
  <testcase classname="placeOrder.placeOrder" name="checkPageLoad" time="0.168"/>
  <testcase classname="placeOrder.placeOrder" name="perform_Search" time="3.105"/>
  <testcase classname="placeOrder.placeOrder" name="perform_ProductCheckout" time="6.295"/>
  <testcase classname="placeOrder.placeOrder" name="perform_Login" time="20.855"/>
  <testcase classname="placeOrder.placeOrder" name="perform_payment" time="237.056">
    <failure type="java.lang.AssertionError" message="Payment failed">
      <![CDATA[java.lang.AssertionError: Payment failed
at placeOrder.placeOrder.perform_payment(placeOrder.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- perform_payment -->
</testsuite> <!-- Test -->
